### PR TITLE
add the methods that are not in the graphql resolver and the classes …

### PR DESCRIPTION
**Pull request by Liu-XinYuan**

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is this pr for? Graphql thing is still on going by @peng-yongsheng . 

Others for? 6.x code bases are still developing. Especially backend is not ready.

**Comment by wu-sheng** [comment]
Graphql protocol is still changing too

**Comment by wu-sheng** [comment]
Ci fails.

**Comment by xingxingyu** [comment]
I forget to add code style 。。。

**Pull request merged**
