### PR TITLE
Sync SmartSql provider setting to all of component-libraries.yml

### PR DESCRIPTION
**Pull request by Ahoo-Wang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix

- Related issues

Ref https://github.com/apache/incubator-skywalking/issues/2390
___
### Bug fix
- Bug description.

SmartSql provider setting is not complete

- How to fix?

Sync SmartSql provider setting to all of component-libraries.yml

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is `SmartSql` a client-side component? Do it need a mapping to set server type?

**Comment by Ahoo-Wang** [comment]
@wu-sheng 
SmartSql is the same as MyBaitis. It is not possible to determine which DB the user will end up using. so the server type cannot be mapped.

**Comment by wu-sheng** [comment]
OK. Make sense.

**Comment by wu-sheng** [comment]
Relate to https://github.com/SkyAPM/SkyAPM-dotnet/pull/167

@liuhaoyang I am not sure the plugin code PR result. But since this is harmless, I prefer to merge it first.

**Pull request merged**
