### PR TITLE
optimize code structure for plugin.

### PR DESCRIPTION
**Pull request by JaredTan95**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@ascrutae could you run test for this PR and do review?

**Comment by wu-sheng** [comment]
Look like CI fails somehow?

**Comment by JaredTan95** [comment]
yep...i only updated my base branch. 🤔

**Comment by JaredTan95** [comment]
@wu-sheng I found the wrong start of the CI check.https://travis-ci.org/apache/incubator-skywalking/builds/430950295#L747

**Comment by ascrutae** [comment]
@JaredTan95  I find that the repository url and branch about PR  shows `unknown repository`,  Is that you had delete this repository?

**Comment by wu-sheng** [comment]
@JaredTan95 Please fix this. Otherwise, we have to close this PR.

**Comment by JaredTan95** [comment]
@ascrutae Maybe...because I re-fork it once.

**Comment by JaredTan95** [comment]
I will close this pr.https://stackoverflow.com/questions/36071272/fix-unknown-repository-of-an-opened-pr-after-deleted-the-fork

**Pull request closed without merging**
