### PR TITLE
Add Source++ to powered-by page

### PR DESCRIPTION
**Pull request by wu-sheng**
## CodeBrig, LLC.
[{ Source++ }](https://sourceplusplus.com/)

 Source++ is an open-source automated programming assistant with runtime-aware and context-aware functionality. 
Source++ is an observant-only programming assistant and aims to bridge **application performance management (APM)** solutions and the software developer's integrated development environment (IDE) to enable tighter feedback loops. 

 Use **SkyWalking** as the flagship APM for the project.

---
Ref #443 

Public source, https://github.com/apache/incubator-skywalking/issues/2342#issue-419213823

cc @BFergerson

### CODE REVIEW

**Comment by wu-sheng** [comment]
Ref https://github.com/apache/incubator-skywalking/pull/2386#issuecomment-477380885

**Comment by wu-sheng** [comment]
@BFergerson Feel free to review this PR or approve this.

**Comment by BFergerson** [comment]
@wu-sheng, sorry for all the PRs and thanks for adding Source++ to the powered by :).

I've created a PR here with a more simple description: https://github.com/apache/incubator-skywalking/pull/2433

**Comment by wu-sheng** [comment]
Got it and approve that PR already.

**Pull request closed without merging**
