### PR TITLE
avoid "by zero" exception when all request are error

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
when all request are error,this will throw "by zero" exception which is not desired,so i fix them by add some "if else" to avoid,i have comment it in #1018 

- How to fix?
add "if else"

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by peng-yongsheng** [comment]
Return 0 is not a good idea when calls equals error calls.
Suggest:
1. calls > error calls: 
    - TPS: ( calls -  error calls) / seconds between
    - AVG response time: ( response times - error response times ) / ( calls -  error calls )
1. calls == error calls
    - TPS: calls / seconds between
    - AVG response time: ( response times / calls )

@wu-sheng

**Comment by candyleer** [comment]
i think @peng-yongsheng 's definition for TPS and AVG are properly
otherwise 0 seem suddenly image that when i request several  times for some urls but the data always 0...

**Comment by peng-yongsheng** [comment]
@wu-sheng I choose 1 (calls and avg response time of all calls).  The user will very doubt when the TPS or AVG response times show in the UI. This bug happens calls equals error calls only, we consider that it is a small probability event, but some user hit with this issue whom we communicate by QQ and Github issues. They initiates the call from their applications, but we show the zero in our UI, they will deem the agent not work.
 In the feature, we can discuss about how many metrics will show in UI, but now, fixed the bug only.

**Comment by peng-yongsheng** [comment]
@candyleer I can help you to find all places which need to fixed.

**Comment by candyleer** [comment]
@wu-sheng ok, i will update soon

**Comment by candyleer** [comment]
@peng-yongsheng  great ,tks
i fix this bug in 5 files, please review if there miss any file and is it right ?

**Comment by peng-yongsheng** [comment]
@candyleer 
Notice that there is a main content "**But I dont like change the metric meaning in different condition.**" from me and @wu-sheng.
So we chose the 1 (calls and avg response time of all calls), that means there is not need to use if to decide calls equals error calls. 

You can coded such as 
```
trends.add((int) (durationSum / calls));
```
instead of 
```
if (calls == errorCalls) {
  trends.add((int) (durationSum / calls));
} else {
  trends.add((int) ((durationSum - errorDurationSum) / (calls - errorCalls)));
}
```
in every situation.

**Comment by candyleer** [comment]
@peng-yongsheng ok, i understand what you mean

**Comment by wu-sheng** [comment]
@candyleer Is already done? Or need further works?

**Comment by candyleer** [comment]
@wu-sheng  already done,it's worked

**Comment by wu-sheng** [comment]
@peng-yongsheng Please review this.

**Pull request merged**
