### PR TITLE
Support namespace in sw3 headers.

### PR DESCRIPTION
**Pull request by wu-sheng**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
#951

### CODE REVIEW

**Comment by wu-sheng** [comment]
@adriancole this is the only header name right now.

**Comment by pragashj** [comment]
blank (ing) on namespace... :)

**Comment by pragashj** [comment]
I meant to say, lgtm!

**Comment by ascrutae** [comment]
This PR has been tested and Here is detail:

First here is process of test cases:
wx20170412-163927 2x

Here is the topology graph.
default

And after I had set the namespace value of persistence service to some value , The topology graph looks like this:
default

**Comment by wu-sheng** [comment]
@ascrutae Thanks. I think the isolation works from the Topology view.

**Pull request merged**
