### PR TITLE
Add Undertow 2.x plugin

### PR DESCRIPTION
**Pull request by chenpengfei**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ * ] New feature provided

Add Undertow 2.x plugin

- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@ascrutae consider this in ga or 5.1?

**Comment by wu-sheng** [comment]
I think you miss a PR to UI. Will not have image in topology.

**Comment by ascrutae** [comment]
@chenpengfei  Just like this: https://github.com/apache/incubator-skywalking-ui/pull/194

**Comment by wu-sheng** [comment]
Also, 6.x and 5.0 agents are compatible. Please send a pr and test to master too. In case cherry pick makes your commits disappear.

**Comment by chenpengfei** [comment]
@acurtain Undertow's logo has already existed. Reference #189. I can find 'skywalking-ui/public/img/node/UNDERTOW.png' in branch feature/5.x

**Comment by wu-sheng** [comment]
@chenpengfei Good to know. Merging this into 5.x and tagging this to GA release. Could you send a new PR to master with the same codes?

**Comment by chenpengfei** [comment]
PR into master, #1699

A new PR into test master too?

**Comment by chenpengfei** [comment]
@wu-sheng The new pr #1700

**Pull request merged**
