### PR TITLE
Fix RuntimeContext

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#1280

problem has been fixed.

because `ContextManager.getRuntimeContext() ` should in thread local context, so i add the judge.
but it seem it's not friendly.

this runtime context my cause some problem like  user should use spring in our instrument server(jetty9.x server or tomcat 7.x 8.x) 

so any one of you have better solution. @wu-sheng @ascrutae 
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@ascrutae  My question is, why Spring plugin add a something to runtime context, but there is no active tracing context? Why is this guaranteed by Spring plugin?

If we added these judges everywhere, then what is the point of Runtime context. RuntimeContext should be guaranteed, because it is expected by other plugins.

**Comment by candyleer** [comment]
i draw a draft for error to explain why error didn't in the context
image

**Comment by wu-sheng** [comment]
> maybe instrument StanardHostValve instead of StandardWrapperValve is another solution?

Thanks for the graph to explain. That makes me easy to understand. If so, I highly recommend to instrument `StanardHostValve`. 

@ascrutae Please run a double check for this.

**Comment by wu-sheng** [comment]
@candyleer Why is this suddenly closed?

**Comment by candyleer** [comment]
emm ,it's a mistake...I just want to reset branch to update

**Comment by wu-sheng** [comment]
Feel free to open a new you, after you are ready.

**Pull request closed without merging**
