### PR TITLE
Fix  #1549,  spring-plugins bug

### LINKED ISSUE #1549: Shadow tracing context. Thread dump error when pressure test
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking: `5.0.0-beta2`
  OS: `CentOS release 6.6 (Final)`
 JRE: `jdk1.7.0_80`

- Which company or project?
  autohome Inc

- What happen?
My application provide a http interface and it will query redis. i added skywalking agent to my application. When qps under 2000 everything is fine but when the qps over 2000 i get some exceptions 
```
WARN 2018-08-15 19:04:36 TracingContext :  More than 300 spans required to create 
java.lang.RuntimeException: Shadow tracing context. Thread dump
	at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:515)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.access$100(TracingContext.java:56)
	at org.apache.skywalking.apm.agent.core.context.TracingContext$7.doProcess(TracingContext.java:334)
	at org.apache.skywalking.apm.agent.core.dictionary.PossibleFound.doInCondition(PossibleFound.java:50)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.createExitSpan(TracingContext.java:330)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:125)
	at org.apache.skywalking.apm.plugin.jedis.v2.JedisMethodInterceptor.beforeMethod(JedisMethodInterceptor.java:37)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
	at redis.clients.jedis.Jedis.get(Jedis.java)
```
obviously， this http interface can not have to many spans. so what's wrong with it?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by ylywyn**
ContextManager.stopSpan(); may not execute

Please answer these questions before submitting pull request

- Why submit this pull request?
Bug fix

- Related issues  

___
### Bug fix
- Bug description.  
- How to fix?

### CODE REVIEW

**Comment by ascrutae** [comment]
I think that this is not the root cause about #1549, I suspect that the problem is caused by that the plugin only stores the `Request` and does not store `Response`。because  of the plugin had check if  `Request` is empty when creating span in `beforeMethod` and the plugin check the `Response` is empty when finish the span in `afterMethod`.

**Comment by wu-sheng** [comment]
> I think that this is not the root cause about #1549, I suspect that the problem is caused by that the plugin only stores the Request and does not store Response。because of the plugin had check if Request is empty when creating span in beforeMethod and the plugin check the Response is empty when finish the span in afterMethod.

Can you provide more detail or another fix for this? If plugin checked, where does the span come from? Any other plugin leak the span?

**Comment by wu-sheng** [comment]
@ylywyn Look like @ascrutae has a different thought, maybe this is not the right way to fix. But the bug is real. 

@ascrutae Please provide the details and things which need @ylywyn to recheck for you.

**Comment by ascrutae** [comment]
@ylywyn Because the `Response` and `Request`  are not stored in `RuntimeContext` at the same time, please see [InvokeForRequestInterceptor](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-commons/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/commons/interceptor/InvokeForRequestInterceptor.java) and [GetBeanInterceptor.java](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/spring-plugins/mvc-annotation-commons/src/main/java/org/apache/skywalking/apm/plugin/spring/mvc/commons/interceptor/GetBeanInterceptor.java), so I think that The `Response` interceptor is not in effect in some version. Could you give the demo to reproduce  this issue. or you can check if the `Response`  is stored in the `RuntimeContext`

**Comment by ylywyn** [comment]
yes,   this is not the root cause about #1549.   context has been removed before  AbstractMethodInterceptor::afterMethod. 

callstack like this:  
6: InvokeForRequestInterceptor::afterMethod  

5: AbstractMethodInterceptor::afterMethod        context[] ?   ContextManager.stopSpan()       
4: AbstractMethodInterceptor::beforeMethod         

3: InvokeForRequestInterceptor::afterMethod      context[SW_REQUEST]  ->   context[]   
2: InvokeForRequestInterceptor::beforeMethod     context[SW_REQUEST]  ->   context[SW_REQUEST, SW_RESPONSE]  

1: InvokeForRequestInterceptor::beforeMethod     context[SW_REQUEST]  ->   context[SW_REQUEST, SW_RESPONSE]

**Comment by ylywyn** [comment]
RUNTIME_CONTEXT management seems to have some problems.

**Comment by ylywyn** [comment]
Moving ContextManager.stopSpan() to finally{} can solve my problem. 
I am not a Java (Spring) developer, so I am not sure that this method AbstractMethodInterceptor::afterMethod will definitely be called under any conditions.

**Comment by ascrutae** [comment]
The 5.0.0-RC will release in this weekend. I hope that this issue will be fixed in this issue , And could you update this PR? @ylywyn

**Comment by wu-sheng** [comment]
> The 5.0.0-RC will release in this weekend. I hope that this issue will be fixed in this issue , And could you update this PR? @ylywyn

@ascrutae Consider sending a separated PR to fix this? I will keep this PR open in next 24 hours, in case @ylywyn still has interested in the update.

**Comment by wu-sheng** [comment]
#1568 provided a better solution to fix this. @ylywyn still thanks for helping.

**Pull request closed without merging**
