### PR TITLE
USE_QUALIFIED_NAME_AS_ENDPOINT_NAME configuration

### PR DESCRIPTION
**Pull request by BFergerson**
- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues: #2342

___
### New feature or improvement
- Describe the details and related test reports.

This gives a more descriptive operation name for the `@RequestMapping` annotations when a specific method or methods are used. For example, `@RequestMapping(value = "/", method = {GET, POST})` will create an operation name of `{GET,POST}/` instead of `/`.

This also adds the configuration values `Config.SpringMVC.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME` and `Config.Toolkit.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME`. These can be used to replace the above URL for a direct reference to the method which has the annotation. This would work for both `@RequestMapping` and `@Trace`.

The integration test is here: https://github.com/SkyAPMTest/agent-auto-integration-testcases/pull/55

### CODE REVIEW

**Comment by wu-sheng** [comment]
@ascrutae What is the status of the test case PR for this? I hope we could finish that and merge both of them.

**Comment by wu-sheng** [comment]
@ascrutae please run the existed spring cases too.

**Comment by wu-sheng** [comment]
@BFergerson I think we changed the default operation names too in this pr, adding get/post in it, right? Then we need to recheck the existingspring cases, maybe need to change expected.yaml

**Comment by BFergerson** [comment]
@wu-sheng, I didn't change what the default endpoint names would be when using `@RequestMapping` without specifying the request method. I don't think any of your integration tests specify the request method so it shouldn't break any of them. With that being said, are you looking for an integration test which expects the `{GET}/` format? Any suggestions for a scenario name?

**Comment by wu-sheng** [comment]
A new case should be better. How about spring-get-annotation?

**Comment by BFergerson** [comment]
@wu-sheng, before reading your suggestions I came up with `spring-with-request-method-op-name-scenario`. How does that sound?

Also, an unforeseen side effect with the way the `PathMappingCache` works (I believe) is that I ended up with endpoint names like:
 - `/requestmethod/{GET}/acceptGetExplicit`
 - `/requestmethod/{GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,TRACE}/acceptAllExplicit`

I think these might be a bit confusing. Suggestions?

**Comment by wu-sheng** [comment]
I think we should put the `get` at the first part. `/{GET}/requestmethod/acceptGetExplicit` should make more sense. Agree?

**Comment by wu-sheng** [comment]
For test case name, I think yours should be good.

**Comment by wu-sheng** [comment]
I forget to use `squash and commit` to this pull request. @apache/skywalking-committers sorry guys.

**Pull request merged**
