### PR TITLE
Correct overriding parent class methods,when method parameters have annotations.More details to see the issue #1740

### PR DESCRIPTION
**Pull request by ni-ze**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ √] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by nize1989** [comment]
wrong branch of last time pr, It should be skywalking-debug branch,sorry for that.

**Comment by wu-sheng** [comment]
@ascrutae Could you run test on this PR?

**Comment by wu-sheng** [comment]
@ni-ze Look like still making a lot of cases failure. Could you recheck about this?

**Comment by ni-ze** [comment]
@wu-sheng ok,I will check it.

**Pull request closed without merging**
