### PR TITLE
Proposal our ROADMAP.

### PR DESCRIPTION
**Pull request by wu-sheng**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] New feature provided

- Describe the details
Proposal a roadmap documents. Feel free to send pull request to branch `doc/roadmap` to add your features, if I miss something.

### CODE REVIEW

**Comment by wu-sheng** [comment]
FYI @otisg . I assume you are interested about this.

**Comment by ascrutae** [comment]
The `Configure delivery` feature  should in the road map.

**Comment by wu-sheng** [comment]
> The Configure delivery feature should in the road map.

@ascrutae Which list do you prefer?

**Comment by ascrutae** [comment]
I think that the `Configure delivery` should be in `Long term features`

**Comment by wu-sheng** [comment]
> I think that the Configure delivery should be in Long term features

@ascrutae Done.

**Comment by wu-sheng** [comment]
@peng-yongsheng @hanahmily 

I add multi-tenancy support in 5.0(highly recommend in 5.0.0-beta) and provide a release plan.

**Pull request merged**
