### PR TITLE
update collector grpc version from 1.10 to 1.14

### PR DESCRIPTION
**Pull request by xingxingyu**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?
update grpc version from 1.10 to 1.14 ，include server and agent
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
See this https://travis-ci.org/apache/incubator-skywalking/builds/421151451?utm_source=github_status&utm_medium=notification ?

**Comment by xingxingyu** [comment]
Seems to be a conflict

**Comment by xingxingyu** [comment]
guava Version does not match，I am going to modify the test.

**Comment by wu-sheng** [comment]
Please fix the tests on your local first.

**Pull request closed without merging**
