### PR TITLE
Added elasticsearch warehouse certification support

### PR DESCRIPTION
**Pull request by klboke**
If you use Alibaba Cloud's elasticsearch service, you need username and password verification.

### CODE REVIEW

**Comment by klboke** [comment]
> @klboke As far as I know, Elasticsearch security just support xPack library. So, is this PR just support Aliyun's Elasticsearch? If not, please provide us a document, let us know how to install a elasticsearch with security that can work together with this PR.

This pr is only compatible with ES services with HTTP Basic simple authentication, and does not change the default mode of services without authentication. The following items are some plugins provided by the community to do the HTTP Basic Simple Authentication for ES.
https://github.com/Asquera/elasticsearch-http-basic
https://github.com/elasticfence/elasticsearch-http-user-auth

**Comment by klboke** [comment]
> If this is just for ali cloud, which would make me concern too. For commercial service, we can't use its protocol as default or inbinding code.

It is not for ES of Alibaba Cloud. There are many applications for http basic authentication of ES. When it is necessary to provide access to the external network, this is an indispensable setting.

**Comment by wu-sheng** [comment]
Could you provide an es document pointing to this protocol?

**Comment by klboke** [comment]
> Could you provide an es document pointing to this protocol?

Find some articles for http authentication processing for ES
https://brudtkuhl.com/blog/securing-elasticsearch/
https://www.rootopen.com/git/5b8ba94964fec049aff8b911
http://guoze.me/2015/05/28/elasticsearch-http-basic-authentication/

**Comment by peng-yongsheng** [comment]
OK, got it, preciate for your contribution.

**Comment by klboke** [comment]
@wu-sheng Supplement the use of the BestQualLevelClient with basic authentication authentication, just to be compatible with those ES services that do http basic authentication, not just provide ES services connected to Alibaba Cloud.

**Comment by wu-sheng** [comment]
From the materials you provided, now my concern is more about misguiding users. When people notice there is auth support in skywalking, they are thinking about xpack, but, actually, we need deploy a proxy to do auth in un-official way. For official, I mean in es official document.

Also, the project document has nothing related to this deployment of proxy.

I prefer this should be introduced as a blog, rather than core inbinding source codes.

@peng-yongsheng What do you think?

**Comment by klboke** [comment]
> From the materials you provided, now my concern is more about misguiding users. When people notice there is auth support in skywalking, they are thinking about xpack, but, actually, we need deploy a proxy to do auth in un-official way. For official, I mean in es official document.
> 
> Also, the project document has nothing related to this deployment of proxy.
> 
> I prefer this should be introduced as a blog, rather than core inbinding source codes.
> 
> @peng-yongsheng What do you think?

By default, this configuration is not enabled. There should be no navigation. I think I should not lose this part of the user who uses the Http Basic authentication service. I will add this blog.

**Comment by peng-yongsheng** [comment]
@wu-sheng My concern is same as your's. The user's first thought is this auth is work with Xpack. But actually not. So, we must explain it to the user over and over again.

**Comment by wu-sheng** [comment]
@klboke I am not arguing for the default values or optional. I am saying, we are going to introduce am unofficial way to our community. This is the core issue I want to be 100% clear and supported by maintainers.

Also, because it is unofficial, the maintainer team has to explain how to use it, especially when people asked why are we doing this. This becomes a question hard to answer.

**Comment by wu-sheng** [comment]
@JaredTan95 thoughts?

**Comment by klboke** [comment]
Http Basic authentication is just a common regular authentication method, not an exclusive authentication mode of Xpack. These two are not necessarily related.

**Comment by wu-sheng** [comment]
Let's wait and see whether others, especially committers, would support this. Since now, we have concerns from two ppmc members for futher support in community.

As a global and widely used oss project, we have to be carefully about this kind of un-official feature.

**Comment by JaredTan95** [comment]
> @JaredTan95 thoughts?

I got this point mostly, this is a common HTTP authentication and also works in Xpack sercurity. @klboke So, We need a blog related and post in [swywalking website](https://github.com/apache/incubator-skywalking-website) to explain it.  Otherwise, we can only provide a blog if this PR not approved by others committers.

**Comment by wu-sheng** [comment]
Could this work with xpack elasticsearch server?

**Comment by klboke** [comment]
> Could this work with xpack elasticsearch server?

Xpack elasticsearch server also provides Http Basic authentication, this pr is only for Http Basic authentication connection

**Comment by wu-sheng** [comment]
Good, if this works for es xpack, really ease my concern. Then I suggest you write the basic auth support document in es storage section. I think it will make people easier yo understand.

**Comment by klboke** [comment]
> Good, if this works for es xpack, really ease my concern. Then I suggest you write the basic auth support document in es storage section. I think it will make people easier yo understand.

Http Basic authentication is a regular authentication method. As this article says https://brudtkuhl.com/blog/securing-elasticsearch/, there are various ways to implement Http Basic, such as plugins, Nginx agents, etc., it should be very good. Understand it. The blog explains this piece, I am also preparing

**Comment by wu-sheng** [comment]
I am thinking more about xpack support. And for document, skywalking official document needs to explain more.

**Comment by wu-sheng** [comment]
The key for pr ready to be merged is, we need make sure es xpack could auth when user active tgis feature. I think Peng has asked once to provide steps to verify.

**Comment by klboke** [comment]
> The key for pr ready to be merged is, we need make sure es xpack could auth when user active tgis feature. I think Peng has asked once to provide steps to verify.

Maybe I started to say that Ali's ES service is a bit wrong. This PR has nothing to do with xpack elasticsearch. It only provides a connection compatible with Http Basic authentication. The current RestHighLevelClient is based on Apache httpClient, and Http Basic is also supported by httpClient.

**Comment by wu-sheng** [comment]
No matter ali cloud or not, inbinding feature requests for the key I mentioned. You need to work with official es API.

**Comment by klboke** [comment]
> No matter ali cloud or not, inbinding feature requests for the key I mentioned. You need to work with official es API.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication

**Comment by wu-sheng** [comment]
Yes. This is the key to let this pr in.😊

**Comment by klboke** [comment]
😊

**Comment by peng-yongsheng** [comment]
> https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication

@klboke Nice, official document for client setting. 
Another question: How to config the server side?

**Comment by klboke** [comment]
> > https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication
> 
> @klboke Nice, official document for client setting.
> Another question: How to config the server side?

The server-side settings are the plug-in projects I have listed above, https://brudtkuhl.com/blog/securing-elasticsearch/ and as this article says, there are several ways to add Http Basic authentication in front of the ES.

**Comment by peng-yongsheng** [comment]
> > > https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication
> > 
> > 
> > @klboke Nice, official document for client setting.
> > Another question: How to config the server side?
> 
> The server-side settings are the plug-in projects I have listed above, https://brudtkuhl.com/blog/securing-elasticsearch/ and as this article says, there are several ways to add Http Basic authentication in front of the ES.

So, server side is no official support.

**Comment by klboke** [comment]
> > > > https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication
> > > 
> > > 
> > > @klboke Nice, official document for client setting.
> > > Another question: How to config the server side?
> > 
> > 
> > The server-side settings are the plug-in projects I have listed above, https://brudtkuhl.com/blog/securing-elasticsearch/ and as this article says, there are several ways to add Http Basic authentication in front of the ES.
> 
> So, server side is no official support.

Yes, the official xpack has support

**Comment by peng-yongsheng** [comment]
> > > > > https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/_basic_authentication.html#_basic_authentication
> > > > 
> > > > 
> > > > @klboke Nice, official document for client setting.
> > > > Another question: How to config the server side?
> > > 
> > > 
> > > The server-side settings are the plug-in projects I have listed above, https://brudtkuhl.com/blog/securing-elasticsearch/ and as this article says, there are several ways to add Http Basic authentication in front of the ES.
> > 
> > 
> > So, server side is no official support.
> 
> Yes, the official xpack has support

No more question. 

@wu-sheng @klboke Although most of the descriptions have been written in this PR, I suggest to provide a guide line document for how to enable this security ability in server side.

**Comment by peng-yongsheng** [comment]
Write a document into the path of /doc/en/.

**Comment by wu-sheng** [comment]
The document should be placed here, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch-6

**Comment by klboke** [comment]
> The document should be placed here, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-storage.md#elasticsearch-6
ok

**Pull request merged**
