### PR TITLE
Remove components define that cannot be supported

### PR DESCRIPTION
**Pull request by liuhaoyang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
what do you mean cannot support?

**Comment by liuhaoyang** [comment]
@wu-sheng EntityFrameworkCore's in-memory database does not have built-in diagostics api,  and a better way is to use the in-memory database provided by sqlite . so I don't plan to support EntityFrameworkCore in-memory database.

**Comment by wu-sheng** [comment]
Cannot support for now or forever? From my perspective, removing some existed IDs is a very dangerous and un-recommended operations.

**Comment by wu-sheng** [comment]
`sqlite`  is a difference component compared with `EntityFrameworkCore's in-memory database`. Right? So, you don't want to support it even after you have more powerfully C++ based codes injection tech?

**Comment by liuhaoyang** [comment]
You're right. It is not appropriate to remove existing IDS.

**Pull request closed without merging**
