### PR TITLE
Added OpenAPM Badge to the readme file

### PR DESCRIPTION
**Pull request by AlexanderWert**
As discussed with @wu-sheng, 

submitting an OpenAPM-Badge for the readme of this project, as Apache SkyWalking is included in the OpenAPM Landscape: https://openapm.io/landscape.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@apache/skywalking-committers Hi all. We have been listed in OpenAPM landscape. https://openapm.io

I want to start a public vote to decide whether we accept this. Open vote for at least 72 hours

Thanks, everyone.

**Comment by wu-sheng** [comment]
My +1

**Comment by liuhaoyang** [comment]
My +1

**Comment by IluckySi** [comment]
+1

**Comment by ascrutae** [comment]
+1

**Comment by hanahmily** [comment]
Great! This's more professional landscape for APM.
+1

**Comment by peng-yongsheng** [comment]
+1

**Comment by clevertension** [comment]
+1

**Comment by qiujiayu** [comment]
+1

**Comment by zhangkewei** [comment]
+1

**Comment by candyleer** [comment]
+1

**Comment by AlexanderWert** [comment]
Thank you @wu-sheng !
Do you think I can now also submit a pull request with the badge for the web site?

**Comment by wu-sheng** [comment]
> Do you think I can now also submit a pull request with the badge for the web site?

I am still thinking about using a new template for our website. Just didn't find a good one. I am just not sure whether is a good time for you to update.

**Comment by wu-sheng** [comment]
@AlexanderWert Done.

**Comment by AlexanderWert** [comment]
@wu-sheng Got it! 
Will wait then for the new template. Would be great if you could let me know!

Thanks!

**Comment by wu-sheng** [comment]
> Will wait then for the new template. Would be great if you could let me know!

Let me find out. I will put an official announcement on Twitter.

**Pull request merged**
