### PR TITLE
Fix occure the NPE when SpringMVC and hystrix work together

### PR DESCRIPTION
**Pull request by ascrutae**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#1238

### CODE REVIEW

**Comment by candyleer** [comment]
ok,I will test in last case

**Comment by ascrutae** [comment]
I had fix this. maybe you can try

**Comment by ascrutae** [comment]
Here is the [test report](https://github.com/SkywalkingTest/agent-integration-test-report/blob/master/2018/5/ascrutae/testReport-master-2018-05-24-07-11.md)

**Comment by wu-sheng** [comment]
> Here is the test report

Thanks. Continue to wait for @candyleer feedback. :)

**Comment by candyleer** [comment]
test passed.
image

image

Thanks.

**Pull request merged**
