### PR TITLE
support rabbitmq plugin

### PR DESCRIPTION
**Pull request by WithLin**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this time test ready?

**Comment by wu-sheng** [comment]
Is this time test ready?

**Comment by wu-sheng** [comment]
Is this time test ready?

**Comment by WithLin** [comment]
no, i am not sure. you can run test by now.

**Pull request closed without merging**
