### PR TITLE
Support ES type/table namespace feature

### PR DESCRIPTION
**Pull request by wu-sheng**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
#932

___
### New feature or improvement
- Describe the details and related test reports.

@peng-yongsheng In order to make the codes more clear, I send this proposal pr (don't merge this even you agree my proposal). 

I add a basic type `Table` for all table descriptions, which will support **namespace**. `TableNamespace` and `NamespaceHandler` are used to access the global config from different storage implementation right now.

If you agree this proposal, I will refactor all sub classes of **CommonTable**, inherit to `Table`, and implement `#tableName` method.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@peng-yongsheng @ascrutae @hanahmily This feature has been provided. Please review.

**Comment by wu-sheng** [comment]
I changed basic `ElasticSearchClient`, and isolate all codes to access type/table name directly. Add `#formatTableName` name to add prefix if `namespace` setting exists.

**Comment by ascrutae** [comment]
This feature had been tested.

**Comment by ascrutae** [comment]
This feature had been tested.

**Pull request merged**
