### PR TITLE
[WIP]Netty http client plugin

### PR DESCRIPTION
**Pull request by JaredTan95**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues
https://github.com/apache/incubator-skywalking/issues/1684
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please provide tests and make them work

**Comment by wu-sheng** [comment]
Is netty http still testing? And how about the integration test cases?

**Comment by JaredTan95** [comment]
related use senario refs: https://github.com/SkywalkingTest/skywalking-agent-testcases/pull/47

**Comment by JaredTan95** [comment]
@github-anymous  Codes in this PR would loss trace data in some case. So, any interests to help this PR merge or another solution?

**Pull request closed without merging**
