### PR TITLE
Lost parameter annotation in method, when enhance the superclass's method in subclass. More details to see the issue #

### PR DESCRIPTION
**Pull request by nize1989**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [√] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#1724
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by nize1989** [comment]
@wu-sheng Thanks for your suggestion，I will take it. But the static method of superclass have not been overrided by subclass in enhanced byte code.

**Comment by wu-sheng** [comment]
> I will take it. But the static method of superclass have not been overrided by subclass in enhanced byte code.

Yes, I think you are right. We may don't need to concern about the static method. :)

**Comment by wu-sheng** [comment]
@nize1989 Based on our autotests, these changes look like making these following cases failure
- Spring-RestTemplate_Annotation_RestAnnotation
- SOFARPC
- PostgreSQL
- Elasticsearch

You could find the target test codes here, https://github.com/SkywalkingTest/skywalking-agent-testcases/tree/master with same name.

I also asked @ascrutae to check, but he is busy these days. So if you have time, please do some tests on your local, and we can discuss what is happening.

**Comment by nize1989** [comment]
@nize1989 ,sorry for reply to you so late.becase of environment, I have not  run the testcases yet. Test as soon as  the conditions are met.

**Comment by wu-sheng** [comment]
@nize1989 I am removing the milestone for now, just for preparing the release of 6.0.0-alpha. We could merge this as soon as it is ready. Don't worry.

**Comment by nize1989** [comment]
OK.thanks.

发自我的 iPhone

**Pull request closed without merging**
