### PR TITLE
Fixed Failure of Enhanced Kafka Interceptor to Acquire SkyWalking DynamicField

### PR DESCRIPTION
**Pull request by Velsson**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix

- Related issues

___
### Bug fix
- Bug description.
 When Kafka Producer is set up, it is enhanced by Kafka Producer. Interceptor Callback, but there is no judgment on getSkyWalkingDynamicField () in Callback Interceptor, resulting in an error of ContextSnapshot't be null.
- How to fix?
 Non empty judgement
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
> When Kafka Producer is set up, it is enhanced by Kafka Producer. Interceptor Callback, but there is no judgment on getSkyWalkingDynamicField () in Callback Interceptor, resulting in an error of ContextSnapshot't be null.

@ascrutae @Velsson My only concern is, when is this field would be NULL? Do we miss something?

**Comment by ascrutae** [comment]
IMO, every callback object will set the `Snapshot` if it had crossed the interceptor of `Producer`,  This issue will cause by the callback not crossed the interceptor of `Producer`, Could you post me more about this issue? e.g.  Kafka version, the demo that it simple and can reproduce this issue.

**Comment by Velsson** [comment]
image
image
Usually, kafkaProducer. intercepters are not used. So it doesn't matter, but when interceptors are set up, the enhanced intercept callback class is used, and skyWalking DynamicField is not set. It's worth noting that it is used by default after 1.1.0.
image

**Comment by wu-sheng** [comment]
@ascrutae Let's submit an issue to track this for new Kafka version.

**Pull request merged**
