### PR TITLE
Add RunnableWrapper

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues
Add RunnableWrapper for there is only `CallableWrapper`
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by candyleer** [comment]
Yes ,this is an `activation ` not a `plugin`.

**Comment by wu-sheng** [comment]
Please make us fix this in this pr.

**Comment by candyleer** [comment]
I am working on this movement now

**Comment by candyleer** [comment]
updated

**Comment by carlvine500** [comment]
@candyleer nice work !

**Pull request merged**
