### PR TITLE
support rabbitmq plugin

### PR DESCRIPTION
**Pull request by WithLin**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@ascrutae Need test on this.

**Comment by ascrutae** [comment]
@WithLin you should resend an new PR about the rabbitMQ plugin and your new PR should base on `feature/5.x branch`. because  the `master` branch of test case project is for  6.x branch of Skywalking currently.

**Comment by WithLin** [comment]
emm. i am fixed it that  i am resend an  new PR  in testcase repo

**Comment by ascrutae** [comment]
The automated test is running. Just wait a moment.

**Comment by ascrutae** [comment]
Here is the [test report](https://github.com/SkywalkingTest/agent-integration-test-report/blob/cc8d6e0c061afcf2e2aa54c9543df48b0735f609/2018/9/WithLin/testReport-feature-5.x-2018-09-28-14-29.md) and [validate log](http://35.227.88.23:49001/job/skywalking-agent-automated-testing/89/artifact/skywalking-agent-testcases/workspace/logs/validate-2018-09-28-14-29.log).

**Comment by wu-sheng** [comment]
@WithLin Don't change other codes in this PR. If you want to refactor, please send a separated PR.

**Comment by WithLin** [comment]
emmm,sorry, I forgot it when I commit it. I just wanted to commitit to my repo, but github added it to this pr. Do I need to make some changes?

**Comment by WithLin** [comment]
@wu-sheng  plugins are  roolbacked. you can see [files changed](https://github.com/apache/incubator-skywalking/pull/1717/files)

**Comment by wu-sheng** [comment]
Why close?

**Comment by wu-sheng** [comment]
I understand the tests are a little difficult, but that is the way we guarantee our codes quality. Sorry for making you feel not good.

**Comment by WithLin** [comment]
en. automated testing  just some details, it is transparent to me. I can't debug how these things run. So it led to some details of the problem, changed and changed, and then wasted time.
Thank you very much for your open source skywalking, which allowed me to learn a lot about distributed tracking.

**Pull request closed without merging**
