### PR TITLE
Fixed UI default port

### PR DESCRIPTION
**Pull request by ainilili**
The default port seems to be 8080

Please answer these questions before submitting pull request

- Why submit this pull request?
- [ x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
UI default port seems to be 8080 but document is listed in 10800
- How to fix?
10800 -》 8080 
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by IanCao** [comment]
ui communicates with collector via port 10800
and ui uses port 8080 as its default http port 
so could you fix doc more clearly ?

**Comment by ainilili** [comment]
> ui communicates with collector via port 10800
> and ui uses port 8080 as its default http port
> so could you fix doc more clearly ?

Sorry, I misunderstood

**Comment by wu-sheng** [comment]
@ainilili If this document triggers some misunderstood, I could adjust this in your PR.

**Comment by wu-sheng** [comment]
But we are moving all supports to 6.x. Could you try to read that?

**Pull request closed without merging**
