### PR TITLE
enabled log4j2 to print traceId both in sync and async mode

### PR DESCRIPTION
**Pull request by ASCE1885**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

[Print traceId to log4j2 failed](https://github.com/apache/incubator-skywalking/issues/1997)

### CODE REVIEW

**Comment by wu-sheng** [comment]
@candyleer Please review this PR.

**Comment by wu-sheng** [comment]
Approve(not merge) this PR when you think it is ready.

**Comment by wu-sheng** [comment]
@ASCE1885 Before people begin to review, please fix your CI first.

**Comment by candyleer** [comment]
Does the threadlocal should been removed finally?

**Comment by wu-sheng** [comment]
@ASCE1885 Please answer @candyleer question, to make sure whether this PR is ready to merge.

**Comment by wu-sheng** [comment]
Any update? This pr stays in silence for last whole week. If no more update in next week, @candyleer you decide to close it or provide by yourself.

**Comment by wu-sheng** [comment]
Closing. No update in half month. Have to. Sorry.

**Pull request closed without merging**
