### PR TITLE
Support Zookeeper plugin

### PR DESCRIPTION
**Pull request by zhaoyuguang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is the status of this?

**Comment by zhaoyuguang** [comment]
> What is the status of this?

In coding

**Comment by zhaoyuguang** [comment]
Ready to do testcase @wu-sheng

**Comment by wu-sheng** [comment]
@WithLin @ascrutae Please review the codes. @ascrutae test case is ready to run.

**Comment by wu-sheng** [comment]
@ascrutae please review the codes

**Comment by wu-sheng** [comment]
@zhaoyuguang I move zookeeper from `NoSQL` group to `distributed coordination` group. I think this should make sense. I am going to merge this after CI passed.

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang I move zookeeper from `NoSQL` group to `distributed coordination` group. I think this should make sense. I am going to merge this after CI passed.

It looks better

**Comment by ascrutae** [comment]
I prefer putting the zookeeper plugin into optional plugin, because of there are useless traces(heart beat) will be generate in cloud environment.

**Comment by wu-sheng** [comment]
@zhaoyuguang I think moving to option makes sense to me. What do you think? If Yes, please move.

**Comment by wu-sheng** [comment]
@ascrutae I think the movement and adjustments are done. Will you run the tests again?

**Comment by zhaoyuguang** [comment]
Yes, the plugin has been placed, the local test has passed, and the testcase needs to be executed again.

**Pull request merged**
