### PR TITLE
Add how to build in eclipse

### PR DESCRIPTION
**Pull request by Xlinlin**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
Add How to build in eclipse

### CODE REVIEW

**Comment by Xlinlin** [comment]
Completed format pom.xml and  add english version

**Comment by Xlinlin** [comment]
Because the compiled RemoteCommonServiceGrpc.java files of collector-remote-grpc-provider project will compile errors.

**Comment by wu-sheng** [comment]
> Because the compiled RemoteCommonServiceGrpc.java files of collector-remote-grpc-provider project will compile errors.

So strange, why, the dependency should exist. Otherwise, `mvn compile`should fail.

**Comment by Xlinlin** [comment]
mvn can be compiled successfully, but grpc source code will display errors, adding guava dependency is normal.

**Pull request merged**
