### PR TITLE
Add jaeger traces support 

### PR DESCRIPTION
**Pull request by wu-sheng**
## Jaeger receiver
Jaeger receiver right now only works in `Tracing Mode`, and no analysis.
Jaeger receiver provides extra gRPC host/port, if absent, sharing-server host/port will be used, then core gRPC host/port.
Receiver requires `jaeger-elasticsearch` storage implementation active. 
Read [this](backend-storage.md#elasticsearch-6-with-jaeger-trace-extension) to know 

Active the receiver.
```yaml
receiver_jaeger:
  default:
    gRPCHost: ${SW_RECEIVER_JAEGER_HOST:0.0.0.0}
    gRPCPort: ${SW_RECEIVER_JAEGER_PORT:14250}
``` 

@yurishkuro I use the agent and `cmd/tracegen` in the main jaeger repo to finish the integration tests.

image

The only concern is, right now, I just do `BASE64` for jaeger traceid. Do you have more official way to make it in String format?

### CODE REVIEW

**Comment by wu-sheng** [comment]
Command to run `agent`
> docker run \
  --rm \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent:1.11 \
  --reporter.grpc.host-port=host.docker.internal:14250

**Comment by wu-sheng** [comment]
Trace gen is built in my local env.  Ref https://github.com/jaegertracing/jaeger/tree/master/internal/tracegen

**Comment by wu-sheng** [comment]
Ref #2044 Pure trace mode added.

**Comment by LvBay** [comment]
Does this mean that I only need to start jaeger-agent and skywalking to achieve link tracking.

Equivalent to skywalking-collector instead of jaeger-collector

@wu-sheng

**Pull request merged**
