### PR TITLE
bugfix:no data collected after application started

### PR DESCRIPTION
**Pull request by carlvine500**
版本:skywalking 3.2.6-2017
bug描述:
使用main方法执行追踪,20+s内不产生监控数据.

分析:
1.DiscoveryRestServiceClient.run() 初始执行0s,周期执行60s, 负责初始化RemoteDownstreamConfig.Collector.GRPC_SERVERS

2.GRPCChannelManager.run() 初始执行0s,周期执行30s,使用RemoteDownstreamConfig.Collector.GRPC_SERVERS建立通道

3.ServiceManager.bootedServices是hashmap结构,GRPCChannelManager.run()往往先于DiscoveryRestServiceClient.run()

修复建议:
1.ServiceManager.bootedServices改成LinckedHashMap,保证执行顺序.
2.DiscoveryRestServiceClient.run()首次同步执行

复现办法:
```
public class JedisTest {
    public static void main(String[] args) throws InterruptedException {
        Jedis j = new Jedis("172.31.66.73", 6381);
        //10s内可能收集不着任何数据
        for (int i = 0; i < 10; i++) {
            Thread.sleep(1000L);
            String users = j.get("users");
            System.out.println(users);
        }
        LockSupport.park();
    }
}
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
@carlvine500 I think you should make sure of these things, before we start review:
1. The description should stay in English. Apache project required us to make the project global. And Chinese is hard for other people. Please understand this.
1. Your codes have conflict with the `master` branch, resolve those, please.

**Comment by peng-yongsheng** [comment]
I think you are right. This is a bug when using HashMap.

**Comment by wu-sheng** [comment]
> I think you are right. This is a bug when using HashMap.

I am glad that you have already confirmed this bug. @peng-yongsheng

**Comment by carlvine500** [comment]
please skip this pr, I have created a new https://github.com/apache/incubator-skywalking/pull/794

**Pull request closed without merging**
