### PR TITLE
Mysql style storage implementation

### PR DESCRIPTION
**Pull request by wu-sheng**
Hi everyone,

I just finish the codebase of MySQL style storage implementation based on existed H2 implementation. Do following adjustments
1. SQL syntax follows MySQL protocol
1. Add missed DAO implementations in H2.
1. Add indexes for each table.

When in MySQL storage implementation, the settings file is independence from the `application.yml`. You need only set this
```yaml
storage:
  mysql:
```

And you have another setting file, named `datasource-setting.properties` with following contents
```

jdbcUrl=jdbc:mysql://localhost:3306/swtest
dataSource.user=root
dataSource.password=root@1234
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.useServerPrepStmts=true
dataSource.useLocalSessionState=true
dataSource.rewriteBatchedStatements=true
dataSource.cacheResultSetMetadata=true
dataSource.cacheServerConfiguration=true
dataSource.elideSetAutoCommits=true
dataSource.maintainTimeStats=false
```

If anyone wants to implement other SQL based implementation, I suggest following this way too.

The tests haven't been done. I will only ask for merge this at least MySQL tested.
@candyleer @YunaiV @JaredTan95 You may be interested in this too.

### CODE REVIEW

**Comment by wu-sheng** [comment]
I added this document for MySQL storage

## MySQL
Active MySQL as storage, set storage provider to **mysql**. 

**NOTICE:** MySQL driver is NOT allowed in Apache official distribution and source codes. 
Please download MySQL driver by yourself. Copy the connection driver jar to `oap-libs`.

```yaml
storage:
  mysql:
```

All connection related settings including link url, username and password
are in `databsource-settings.properties`. 
This setting file follow [HikariCP](https://github.com/brettwooldridge/HikariCP) connection pool document.

**Comment by wu-sheng** [comment]
Also add storage extension document

# Extend storage
SkyWalking has already provided several storage solutions. In this document, you could 
learn how to implement a new storage easily. 

## Define your storage provider
1. Define a class extends `org.apache.skywalking.oap.server.library.module.ModuleProvider`.
2. Set this provider targeting to Storage module.
```java
@Override 
public Class<? extends ModuleDefine> module() {
    return StorageModule.class;
}
```

## Implement all DAOs
Here is the list of all DAO interfaces in storage
1. IServiceInventoryCacheDAO
1. IServiceInstanceInventoryCacheDAO
1. H2EndpointInventoryCacheDAO
1. H2NetworkAddressInventoryCacheDAO
1. IBatchDAO
1. StorageDAO
1. IRegisterLockDAO
1. H2TopologyQueryDAO
1. IMetricQueryDAO
1. ITraceQueryDAO
1. IMetadataQueryDAO
1. IAggregationQueryDAO
1. IAlarmQueryDAO
1. IHistoryDeleteDAO

## Register all service implementations
In `public void prepare()`, use `this#registerServiceImplementation` method to do register binding your implementation with the above interfaces.

## Example
Take `org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider` 
or `org.apache.skywalking.oap.server.storage.plugin.jdbc.mysql.MySQLStorageProvider`  as a good example.

**Comment by wu-sheng** [comment]
@ascrutae @peng-yongsheng I just made the codes work in my local MySQL 8.x in single mode.

**Comment by wu-sheng** [comment]
Also, when you review codes, I also fixed several backend bugs in this PR too. MySQL storage implementation makes this bugs more clear. FYI @peng-yongsheng

**Comment by wu-sheng** [comment]
Another bug fixed, delete *_inventory models based on TTL, because the `#deleteHistory` attribute is not used in DataTTLKeeperTimer.

Also `SegmentRecord#deleteHistory` should stay in `true`(default)

**Comment by candyleer** [comment]
Smoke Test has passed in mysql 5.7 today ,I will add some more test tomorrow..

**Comment by wu-sheng** [comment]
> Smoke Test has passed in mysql 5.7 today ,I will add some more test tomorrow..

Great. @candyleer I have tested in MySQL 8.0.13 . How about approve this and merged? Then we continue to chase the issues.

**Comment by wu-sheng** [comment]
@candyleer Thanks. Please send issue and pull request, if you find any other issue. 

FYI @JaredTan95 Same for you.

**Pull request merged**
