### PR TITLE
add spring cloud fegin 2.x support

### PR DESCRIPTION
**Pull request by IanCao**
the processing mode of spring cloud fegin 2.x is same as spring cloud fegin 1.x .. the different of them is ENHANCE_CLASS in Instrumentation

### CODE REVIEW

**Comment by wu-sheng** [comment]
Let's add new test cases too. @ascrutae Please review.

@IanCao I think you have known all the processes now.

**Comment by wu-sheng** [comment]
Here is the test case develop document, https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/docs/how-to-write-a-plugin-testcase-cn.md . 

I am not sure you need the whole new test cases, or just add new versions to old cases.

**Comment by wu-sheng** [comment]
And CI fails?

**Comment by IanCao** [comment]
ok i'll do that tomorrow

**Comment by wu-sheng** [comment]
CI is still failing. Ping me when CI and test case PR is ready.

**Comment by IanCao** [comment]
> CI is still failing. Ping me when CI and test case PR is ready.

ok

**Comment by wu-sheng** [comment]
Please use separated pr to add Chinese document.

**Comment by IanCao** [comment]
> Any update?

just update test case..im busy recently. and i have prepared this test case.but im not sure  whether test case works well or not..i'll check the checkstyle of  test case and its correctness

**Comment by wu-sheng** [comment]
Sure. Take your time. I am tracking all open pr status. And version have updated to 6.0 ga. Your plugin version needs to update too, in order to make ci pass.

**Pull request closed without merging**
