### PR TITLE
Fix inherit spring controller blocking error

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
when spring controller inherit exist will produce this blocking error in business code,param cannot be set.
```
java.lang.IllegalArgumentException: Name for argument type [java.lang.Integer] not available, and parameter name information not found in class file either.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:168)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:145)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:94)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$7lyOlrxo(InvocableHandlerMethod.java:128)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest$original$7lyOlrxo$accessor$wlLDCHc4(InvocableHandlerMethod.java)
	at org.springframework.web.method.support.InvocableHandlerMethod$auxiliary$vLrzxjQq.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.example.test.CustomFilter.doFilter(CustomFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke$original$UzEo7A0e(StandardHostValve.java:140)
	at org.apache.catalina.core.StandardHostValve.invoke$original$UzEo7A0e$accessor$aTwcUwgc(StandardHostValve.java)
	at org.apache.catalina.core.StandardHostValve$auxiliary$PnfLXAZY.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

example code
ParentController.java
```java
@RestController
@RequestMapping("parent")
public class ParentController {

    @GetMapping("a")
    public String a(Integer b) {
        return "parent-a" + b;
    }
}
```
ChildController.java
```java
@RestController
@RequestMapping("child")
public class ChildController extends ParentController {

}
```

 ## Without Agent
image

## With Agent

image

will reproduce this error
- How to fix?

For the root reason is  bytebuddy enhace bytecode by enhancing some methods which is not declared by the own Class( some from parent Class),so spring will get wrong method name in RequestMapping.so the solution is making method enhancement is declared by current Class(TypeDescription in bytebuddy)
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
CI fails.

**Comment by wu-sheng** [comment]
@candyleer Glad to have you back.

**Comment by wu-sheng** [comment]
You keep silence in several months.😊

**Comment by wu-sheng** [comment]
@candyleer Could you provide a test case in plugin test repo to verify the situation described in this PR?

**Comment by candyleer** [comment]
ok

**Comment by candyleer** [comment]
it seems only branch 5.x can pass the auto test ,but this branch is based on master

**Comment by wu-sheng** [comment]
Don't worry. We are taking care of this. This is an test tool issue. 6.0 agent.conf changed.

**Comment by ascrutae** [comment]
Here is the [validate log](http://35.227.88.23:49001/job/skywalking-agent-automated-testing/34/artifact/skywalking-agent-testcases/workspace/logs/validate-2018-09-12-13-18.log)

**Comment by candyleer** [comment]
i will check later

**Comment by wu-sheng** [comment]
@candyleer See this commit. https://github.com/apache/incubator-skywalking/commit/433cf3a8fdebbcdbc4a6a4c0316c22c49b814933#diff-4965392f107631d9437a23c5f4366d9dR73 . I think this line may fix. Could you give a try?

**Comment by candyleer** [comment]
I am test in my cast now

**Comment by candyleer** [comment]
@wu-sheng  #1682 fix this bug and it works for me

**Comment by wu-sheng** [comment]
@candyleer Could you post a comment at #1682 and close this one?

**Comment by candyleer** [comment]
it seems this issue also exists due to https://github.com/apache/incubator-skywalking/pull/1682/commits/2f5f88c81713edc9e1760669496cf2057f64bd13

**Comment by wu-sheng** [comment]
See #1740 I think thay should fix this, could you confirm?

**Comment by candyleer** [comment]
> See #1740 I think thay should fix this, could you confirm?

yeah，#1740 fix this issue as same as this pr , but it cause some plugin running failure, so i am trying to find the root cause.

**Comment by wu-sheng** [comment]
Which failures? #1740 passed all cases should be passed in current codebase. New case for inherit is being prepared by Xin Zhang.

**Comment by wu-sheng** [comment]
My mistake. See #1875

**Comment by candyleer** [comment]
close this pr,move to #1875

**Pull request closed without merging**
