### PR TITLE
fix 5.x too many open files

### PR DESCRIPTION
**Pull request by IanCao**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by peng-yongsheng** [comment]
From your changes seems ok, but I don't sure it was fixed this issue really. 
Do you confirm the number of the file open handles by the collector's process? Recommended you refer to the following step for check.  
1. Check the number of the file open handles after collector startup.
1. Change the buffer config in application.yml. 
`
bufferOffsetMaxFileSize: 1 # Unit is MB
bufferDataMaxFileSize: 1 # Unit is MB
bufferFileCleanWhenRestart: true
`
1. Send more than 1k trace segments with different operator name to trigger the trace buffer reader and writer operate. And set a too long string into span's log, it could make the trace segment's length too long to let the buffer manager open more files.
1. Check the number of the file open handles after segments send finish.
1. Make sure the number of the file open handles is same as the number after collector startup.

**Comment by IanCao** [comment]
yes. it was tested online over 40000 cpm. the number of the offset file handles linear decrease.

**Comment by IanCao** [comment]
the problem is the randomAccessFile is always null in FileUtils.writeAppendToLast(File file, RandomAccessFile randomAccessFile, String value), so the process create new RandomAccessFile again and again without close

**Comment by peng-yongsheng** [comment]
@IanCao OK, thanks very much. Travis CI build not complete. A check error, please check it. I will merge your pr after CI successful.

**Pull request merged**
