### PR TITLE
Support canal plugin

### PR DESCRIPTION
**Pull request by WithLin**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
For my understanding of canal, I assume, we at least need source and destination of canal data sync. Am I right? Where is the entry span? And the trace will continue between source and destination?

**Comment by WithLin** [comment]
>Could you describe the use of this plugin?

Of course, because the canal client needs to pull data from the canal-server, the canal client is just a pull operation. This plugin can record the current time, batchSize, and destination.

>In the codes, the only thing it did, is creating an exit span, but no header related works. So this plugin would't deal with propagation. As the result, the only thing people will get the target nodes in topology.
Then, my questions is, who will take the responsibilities to build parent span? Or is there anyone?

In my view,I also thought about this problem at the time. In our project that we have a lot of canal-server nodes. I need to see their dependencies in the topology diagram. I also thought about using the LocalSpan form to write this plugin, but Should this not show topology dependencies? The previous one said that canal-client is just an operation to pull data. So I don't think it needs to handle propagation, but do you think LocalSpan is more suitable? If you think it is, then I will change codes.

>Also, you need to add lib and versions into the supported list after we could be sure about the purpose of this plugin. 

i will chage it.

>For my understanding of canal, I assume, we at least need source and destination of canal data sync. Am I right? Where is the entry span? And the trace will continue between source and destination?

No, canal-client is only for the convenience of operation and maintenance canal-server, canal-client needs to synchronize data from canal-server, canal-server supports multi-database synchronization, each database  is a destination for canal-client.canal-server has a multi-instance concept,

**Comment by wu-sheng** [comment]
From your description, if client runs in pull mode, it should use entry span, with peer tag in it. And then we need a server side adjustment to support this in topology.

**Comment by wu-sheng** [comment]
@ascrutae From discussion, this related to #1805 somehow.

**Comment by wu-sheng** [comment]
@ascrutae Please do code review.

**Comment by ascrutae** [comment]
@WithLin  I saw the canal has support [multiple IP connection mode](https://github.com/alibaba/canal/wiki/ClientAPI). and I cannot see instrumentation about the multiple IP mode, Is that miss it, or this plugin don't support it ?

**Comment by ascrutae** [comment]
it maybe cause another problem about topology graph. If you don’t take all
peers. Maybe the topology graph will show that one node calls multiple
MySQL node. I think this is a problem.

**Comment by ascrutae** [comment]
And maybe it's an cluster.

**Comment by WithLin** [comment]
>. Maybe the topology graph will show that one node calls multiple
MySQL node

What have to do with mysql node?  It’s  canal node.

> I think this is a problem.

yes, you are right. 

>And maybe it's an cluster.
But it is possible that a node is dead, it is not a cluster.

In my opinion, as time goes by that the dead nodes will disappear in dashboard.
Is my idea correct?

**Comment by ascrutae** [comment]
I don't think so. IMO, if those peers is an cluster , and it should be an node in the topology graph. if one node of those peer is broker,  maybe we can take another way to let the user know, e.g. alarm

**Comment by WithLin** [comment]
hi @ascrutae 
Thx for your answer.i already fix it that it  support multiple IP .

**Pull request merged**
