### PR TITLE
Replaced ObjectUtils for Objects methods

### PR DESCRIPTION
**Pull request by nikitap492**
- Related pr  https://github.com/apache/incubator-skywalking/pull/1069
Replaced ObjectUtils for Objects methods

### CODE REVIEW

**Comment by wu-sheng** [comment]
@peng-yongsheng What do you thing?

**Comment by peng-yongsheng** [comment]
@nikitap492 Thank you for your contribution.

**Comment by wu-sheng** [comment]
@nikitap492 Please be advised about @peng-yongsheng 's commit: https://github.com/apache/incubator-skywalking/pull/1094/commits/68b9055a48dc5bbac1149d5569a04b7548791094 , which reverses your prev commit. We prefer don't use this style of codes, to make codes easier to read.

**Comment by wu-sheng** [comment]
@peng-yongsheng Your reverse is not right.

**Pull request merged**
