### PR TITLE
chinese documents translation, sync with english

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance
- [x] document

- Related issues
#1024 
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by candyleer** [comment]
Direct uplink translation maybe not correct.please check

**Comment by candyleer** [comment]
@peng-yongsheng  travis-ci has failed cause of:
```
error: Server does not allow request for unadvertised object cad43d3d6a0bfa3cc5cb4e9a58f3ae2e3dee73c7
Fetched in submodule path 'skywalking-ui', but it did not contain cad43d3d6a0bfa3cc5cb4e9a58f3ae2e3dee73c7. Direct fetching of that commit failed.
```
dose it relate with this pr? this make me confused when i just update the documents only

**Comment by wu-sheng** [comment]
> dose it relate with this pr? this make me confused when i just update the documents only

You update submodule to another unexisted commitid. My guess, it is related to your fork repo. So please reverse it.

**Comment by candyleer** [comment]
@wu-sheng yeah,i found it ,i will remove this dirty commit and commit again

**Pull request merged**
