### PR TITLE
fix classloader dead lock in jdk7+

### PR DESCRIPTION
**Pull request by IanCao**
image

when some  projects which  start slowly in lower machine, The classLoader  dead lock will appear as above.

as shown above, There is two Threads process when project start.  Two Thread process crosswise normally, but in some slow scenes, Two Thread process in the meantime, so this create classloader dead lock

### CODE REVIEW

**Comment by wu-sheng** [comment]
This is a very important bug fix we need to review. And relate to jvm7+ parallel classloader.

**Comment by wu-sheng** [comment]
When I dive into the `ClassLoader`, from jvm7, if other class loaders run in parallel mode, and accidentally they ask AgentClassLoader to init a plugin interceptor concurrently. May trigger this lock. 

The related codes are here
```
    // This method is invoked by the virtual machine to load a class.
    private Class<?> loadClassInternal(String name)
        throws ClassNotFoundException
    {
        // For backward compatibility, explicitly lock on 'this' when
        // the current class loader is not parallel capable.
        if (parallelLockMap == null) {
            synchronized (this) {
                 return loadClass(name);
            }
        } else {
            return loadClass(name);
        }
    }
```

The deadlock info is here

**Comment by wu-sheng** [comment]
@ascrutae @candyleer @JaredTan95 This is a very special bug and fix way. I think, for now, this is the right solution. `AgentClassLoader` is not parallel sensitive. It is OK to open this if possible.

**Comment by yuanjinzhong** [comment]
> deadlock info

how to print the beautiful deadlock info, does you use arthas ? thanks

**Comment by yuanjinzhong** [comment]
> > deadlock info
> 
> how to print the beautiful deadlock info, does you use arthas ? thanks

@wu-sheng

**Pull request merged**
