### PR TITLE
Fix rat check in ui local fonts file

### PR DESCRIPTION
**Pull request by candyleer**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
add local font file in pr https://github.com/apache/incubator-skywalking-ui/pull/158
exclude this font file from `apache-rat-plugin` to avoid check failed.

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Does this https://github.com/apache/incubator-skywalking-ui/pull/158 trigger CI fail if we sync the submodule?

**Comment by candyleer** [comment]
@wu-sheng yes. I test in my develop env so I find this issue.

**Comment by wu-sheng** [comment]
I am notified these svg files are released under MIT, so we can redistributed those, and add Apache license header in those.

So, I am closing this pr.

**Comment by candyleer** [comment]
yes, i will make a pr to ui project to add apache license for these files

**Pull request closed without merging**
